import type { SuperSystemConfig, ThemeColors } from "./types.js";

function kebab(value: string): string {
  return value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function colorVariables(colors: ThemeColors): string {
  return Object.entries(colors)
    .map(([key, value]) => `  --ss-color-${kebab(key)}: ${value};`)
    .join("\n");
}

function densityFactor(density: SuperSystemConfig["spacing"]["density"]): number {
  return density === "compact" ? 0.8 : density === "spacious" ? 1.2 : 1;
}

export function compileTheme(config: SuperSystemConfig): string {
  const factor = densityFactor(config.spacing.density);
  const unit = config.spacing.unit * factor;
  const dark = colorVariables(config.themes.dark);

  return `/* Generated by Super System. Edit super-system.json, then run: super-system build-theme */
:root {
${colorVariables(config.themes.light)}
  --ss-font-sans: ${config.typography.fontSans};
  --ss-font-mono: ${config.typography.fontMono};
  --ss-font-size-base: ${config.typography.baseSize};
  --ss-line-height: ${config.typography.lineHeight};
  --ss-space-1: ${unit}px;
  --ss-space-2: ${unit * 2}px;
  --ss-space-3: ${unit * 3}px;
  --ss-space-4: ${unit * 4}px;
  --ss-space-6: ${unit * 6}px;
  --ss-radius-sm: ${config.radius.sm};
  --ss-radius-md: ${config.radius.md};
  --ss-radius-lg: ${config.radius.lg};
  --ss-radius-full: ${config.radius.full};
  --ss-target-min: ${config.accessibility.minimumTargetSize}px;
  color-scheme: light;
}

:root[data-theme="dark"] {
${dark}
  color-scheme: dark;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${dark}
    color-scheme: dark;
  }
}

${config.accessibility.reducedMotion ? `@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    scroll-behavior: auto !important;
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}` : ""}
`;
}
