import type { ElevationConfig, SuperSystemConfig, SurfaceConfig, ThemeColors, TypographyScale, TypographyWeights } from "./types.js";
import { defaultTheme } from "./default-theme.js";
import { buildGoogleFontsImport } from "./google-fonts.js";

function kebab(value: string): string {
  return value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function mergeThemeColors(theme: ThemeColors, defaults: ThemeColors): ThemeColors {
  return { ...defaults, ...theme };
}

function mergeTypographyScale(scale: Partial<TypographyScale> | undefined): TypographyScale {
  return { ...defaultTheme.typography.scale, ...scale };
}

function mergeTypographyWeights(weight: Partial<TypographyWeights> | undefined): TypographyWeights {
  return { ...defaultTheme.typography.weight, ...weight };
}

function mergeElevation(elevation: Partial<ElevationConfig> | undefined): ElevationConfig {
  return { ...defaultTheme.elevation, ...elevation };
}

function mergeSurfaces(surfaces: Partial<SurfaceConfig> | undefined): SurfaceConfig {
  return { ...defaultTheme.surfaces, ...surfaces };
}

function colorVariables(colors: ThemeColors): string {
  return Object.entries(colors)
    .map(([key, value]) => `  --ss-color-${kebab(key)}: ${value};`)
    .join("\n");
}

function densityFactor(density: SuperSystemConfig["spacing"]["density"]): number {
  return density === "compact" ? 0.8 : density === "spacious" ? 1.2 : 1;
}

function sharedThemeVariables(config: SuperSystemConfig): string {
  const scale = mergeTypographyScale(config.typography.scale);
  const weight = mergeTypographyWeights(config.typography.weight);
  const elevation = mergeElevation(config.elevation);
  const surfaces = mergeSurfaces(config.surfaces);
  const bodySize = config.typography.baseSize || defaultTheme.typography.baseSize;

  return `${Object.entries(scale)
    .map(([key, value]) => `  --ss-font-size-${key}: ${key === "body" ? bodySize : value};`)
    .join("\n")}
  --ss-font-weight-heading: ${weight.heading};
  --ss-font-weight-body: ${weight.body};
  --ss-font-weight-strong: ${weight.strong};
  --ss-line-height-heading: ${config.typography.headingLineHeight ?? defaultTheme.typography.headingLineHeight};
  --ss-surface-gradient-tint: ${surfaces.gradientTint}%;
  --ss-surface-gradient-angle: ${surfaces.gradientAngle}deg;
  --ss-surface-gradient: linear-gradient(
    var(--ss-surface-gradient-angle),
    color-mix(in srgb, var(--ss-color-primary) var(--ss-surface-gradient-tint), var(--ss-color-background)),
    var(--ss-color-background)
  );
  --ss-elevation-shadow: ${elevation.shadow};
  --ss-elevation-shadow-hover: ${elevation.shadowHover};
  --ss-elevation-lift: ${elevation.lift};
  --ss-overlay-backdrop: color-mix(in srgb, var(--ss-color-foreground) 45%, transparent);
  --ss-overlay-shadow: 0 16px 40px color-mix(in srgb, var(--ss-color-foreground) 14%, transparent);`;
}

export function compileTheme(config: SuperSystemConfig): string {
  const factor = densityFactor(config.spacing.density);
  const unit = config.spacing.unit * factor;
  const light = mergeThemeColors(config.themes.light, defaultTheme.themes.light);
  const dark = mergeThemeColors(config.themes.dark, defaultTheme.themes.dark);
  const darkCss = colorVariables(dark);
  const shared = sharedThemeVariables(config);

  return `${buildGoogleFontsImport(config)}

/* Generated by Super System. Edit super-system.json, then run: super-system build-theme */
:root {
${colorVariables(light)}
  --ss-font-sans: ${config.typography.fontSans};
  --ss-font-mono: ${config.typography.fontMono};
  --ss-font-size-base: ${config.typography.baseSize};
  --ss-line-height: ${config.typography.lineHeight};
${shared}
  --ss-space-1: ${unit}px;
  --ss-space-2: ${unit * 2}px;
  --ss-space-3: ${unit * 3}px;
  --ss-space-4: ${unit * 4}px;
  --ss-space-6: ${unit * 6}px;
  --ss-radius-sm: ${config.radius.sm};
  --ss-radius-md: ${config.radius.md};
  --ss-radius-lg: ${config.radius.lg};
  --ss-radius-full: ${config.radius.full};
  --ss-target-min: ${config.accessibility.minimumTargetSize}px;
  color-scheme: light;
}

:root[data-theme="dark"] {
${darkCss}
  color-scheme: dark;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkCss}
    color-scheme: dark;
  }
}

${config.accessibility.reducedMotion ? `@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    scroll-behavior: auto !important;
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}` : ""}
`;
}
