import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  ADAPTER_GENERATOR_VERSION,
  AUDIT_RULE_CATALOG,
  GENERATED_SECTION_BEGIN,
  GENERATED_SECTION_END
} from "@super-system/rules";
import { defaultPolicy, pathExists, readPolicy, writePolicy } from "./policy.js";

export type AdapterTarget = "agents-md";

export interface AdapterGenerateOptions {
  target: AdapterTarget;
  dryRun?: boolean;
  force?: boolean;
}

export interface AdapterGenerateResult {
  target: AdapterTarget;
  file: string;
  content: string;
  wrote: boolean;
  preview: boolean;
}

function buildAgentsSection(): string {
  const components = [
    "Button", "Input", "Textarea", "Label", "Checkbox", "Radio group", "Switch", "Slider", "Select",
    "Alert", "Spinner", "Skeleton", "Tooltip", "Badge", "Card", "Tabs", "Accordion", "Breadcrumb",
    "DropdownMenu", "Pagination", "Dialog", "Drawer", "Popover", "Toast", "Table", "Icon", "ThemeProvider"
  ];

  const rules = AUDIT_RULE_CATALOG.map((rule) => `- **${rule.id}** — ${rule.message}`).join("\n");

  return [
    GENERATED_SECTION_BEGIN,
    "<!-- Generated by @super-system/cli — do not edit this section manually. -->",
    "",
    "## Super System (generated)",
    "",
    "Use components from `@super-system/react` for UI controls instead of raw HTML elements.",
    "",
    "### Components",
    "",
    components.join(", ") + ".",
    "",
    "### Rules",
    "",
    "- Treat `super-system.json` as the single source of truth.",
    "- Never edit `.super-system/theme.css` manually.",
    "- Use semantic Super System CSS variables instead of hard-coded colors or spacing.",
    "- After UI work, run `npx @super-system/cli audit` and `check-contrast`.",
    "",
    "### Audit rules enforced by policy",
    "",
    rules,
    "",
    `Generator version: ${ADAPTER_GENERATOR_VERSION}`,
    GENERATED_SECTION_END
  ].join("\n");
}

export function mergeGeneratedSection(existing: string, generatedBody: string): string {
  const begin = existing.indexOf(GENERATED_SECTION_BEGIN);
  const end = existing.indexOf(GENERATED_SECTION_END);

  if (begin >= 0 && end > begin) {
    const after = end + GENERATED_SECTION_END.length;
    return `${existing.slice(0, begin)}${generatedBody}${existing.slice(after).replace(/^\n/, "\n")}`;
  }

  const trimmed = existing.trimEnd();
  if (!trimmed) return `${generatedBody}\n`;
  return `${trimmed}\n\n${generatedBody}\n`;
}

export async function generateAdapter(
  cwd: string,
  options: AdapterGenerateOptions
): Promise<AdapterGenerateResult> {
  if (options.target !== "agents-md") {
    throw new Error(`Unsupported adapter target: ${options.target}`);
  }

  const file = path.join(cwd, "AGENTS.md");
  const generatedBody = buildAgentsSection();
  const existing = (await pathExists(file)) ? await readFile(file, "utf8") : "";
  const content = mergeGeneratedSection(existing, generatedBody);

  if (!options.dryRun) {
    await writeFile(file, content, "utf8");
    const policy = (await readPolicy(cwd)) ?? defaultPolicy();
    policy.adapters = {
      generatorVersion: ADAPTER_GENERATOR_VERSION,
      lastGeneratedAt: new Date().toISOString()
    };
    await writePolicy(cwd, policy);
  }

  return {
    target: options.target,
    file: "AGENTS.md",
    content,
    wrote: !options.dryRun,
    preview: options.dryRun ?? false
  };
}

export function formatAdapterResult(result: AdapterGenerateResult): string {
  if (result.preview) {
    return ["Super System adapter preview (AGENTS.md):", "", result.content].join("\n");
  }
  return `Wrote generated Super System section to ${result.file}.`;
}
